### ISSUE TITLE
Add compiled version for Windows

### ISSUE THREAD

**Issue by Bellisario** [dhhruv/Tic-Tac-Toe#1]
Why don't add a compiled version for Windows? This is a simple app, but very beautiful!

**Comment by dhhruv** [comment]
Thanks @Bellisario. Yeah, as per your request I've added a compiled version for Windows. You can find that under the [Releases](https://github.com/dhhruv/Tic-Tac-Toe/releases/tag/1.0.0) Section. At initial stage, even I thought of making one but the compiled version bundles up all the pygame modules and so costs about 40 MB so I didn't release it as one.

**Comment by Bellisario** [comment]
Thanks @dhhruv!
